### ISSUE TITLE
Build error on Mac non-x86 machine

### ISSUE THREAD

**Issue by coopernetes** [finos/git-proxy#655]
**Describe the bug**
When running `npm install` on the project, the following dependencies are missing when running the frontend on a non-x86/x64 machine 
(such as a MacBook with M1/M2 hardware).

```bash
[1] Error: The package "@esbuild/darwin-arm64" could not be found, and is needed by esbuild.
[1] 
[1] If you are installing esbuild with npm, make sure that you don't specify the
[1] "--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
[1] of "package.json" is used by esbuild to install the correct binary executable
[1] for your current platform.
[1]     at generateBinPath (/Users/tom/git-proxy/node_modules/esbuild/lib/main.js:1899:15)
[1]     at esbuildCommandAndArgs (/Users/tom/git-proxy/node_modules/esbuild/lib/main.js:1969:33)
[1]     at ensureServiceIsRunning (/Users/tom/git-proxy/node_modules/esbuild/lib/main.js:2133:25)
[1]     at build (/Users/tom/git-proxy/node_modules/esbuild/lib/main.js:2025:26)
[1]     at bundleConfigFile (file:///Users/tom/git-proxy/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66209:26)
[1]     at loadConfigFromFile (file:///Users/tom/git-proxy/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66185:31)
[1]     at resolveConfig (file:///Users/tom/git-proxy/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65782:34)
[1]     at _createServer (file:///Users/tom/git-proxy/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65051:26)
[1]     at createServer (file:///Users/tom/git-proxy/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65048:12)
[1]     at CAC.<anonymous> (file:///Users/tom/git-proxy/node_modules/vite/dist/node/cli.js:763:30)
[1] npm run client exited with code 1
```

**To Reproduce**
1. Run `npm install` with the finos/git-proxy repo checked out on an non-Intel Mac system.

**Expected behavior**
The project can be installed on most typical development machines (Windows, Mac, Linux) and hardware (amd64, arm64).

**Comment by JamieSlome** [comment]
@coopernetes - we should probably move to containerised testing environment to ensure consistency of install and usage. Thoughts?

**Comment by coopernetes** [comment]
@JamieSlome a [devcontainers](https://containers.dev/) setup would be a welcome addition. Our internal fork is using this already so we can contribute this back for sure.

Even with a container-based development environment, we still have to support different hardware configurations for these sorts of dependencies.
